### ISSUE TITLE
"TypeError: can't concat str to bytes", when using change-kernel-parameters

### ISSUE THREAD

**Issue by Fornball** [cb-linux/breath#263]
When either replacing the whole command line or appending I get the same error:
```
$ change-kernel-parameters -a quiet
Traceback (most recent call last):
  File "/usr/local/bin/change-kernel-parameters", line 62, in <module>
    generateNewKernel()
  File "/usr/local/bin/change-kernel-parameters", line 41, in generateNewKernel
    kernelPartition = rootDevice[:-1] + '1'
TypeError: can't concat str to bytes
```

**Comment by Fornball** [comment]
Nevermind, I just saw the code is in python so Im gonna fix it real quick and create a pr
